# Generated by Django 5.2.12 on 2026-03-12 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('CROP', 'Crop Disease'), ('LIVESTOCK', 'Livestock Disease')], default='CROP', max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Common symptoms of the disease')),
                ('causes', models.TextField(blank=True, help_text='What causes this disease')),
                ('prevention_tips', models.TextField(blank=True)),
                ('severity_level', models.IntegerField(default=3, help_text='1=Low, 5=Critical', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diseases',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='diseases_categor_1a7715_idx'), models.Index(fields=['name'], name='diseases_name_82f10d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(help_text='Village, LGA, State', max_length=255)),
                ('region_code', models.CharField(help_text='e.g., NG-KD (Kaduna), NG-KN (Kano)', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('farm_size_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Farm size in hectares', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farmers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='farmers_phone_n_1ebf5a_idx'), models.Index(fields=['region_code'], name='farmers_region__d1618a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='ML model confidence (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('region_code', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ml_model_version', models.CharField(default='v1.0', max_length=50)),
                ('raw_ml_response', models.JSONField(blank=True, help_text='Full ML service response', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='core.disease')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.farmer')),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dosage', models.TextField(help_text='Recommended dosage')),
                ('application_method', models.TextField(help_text='How to apply the treatment')),
                ('frequency', models.CharField(help_text="e.g., 'Every 7 days'", max_length=255)),
                ('duration', models.CharField(help_text="e.g., '3 weeks'", max_length=255)),
                ('precautions', models.TextField(blank=True)),
                ('effectiveness_rating', models.IntegerField(default=3, help_text='1=Low, 5=Highly Effective', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.disease')),
            ],
            options={
                'db_table': 'treatments',
                'ordering': ['-effectiveness_rating'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('AGRO_DEALER', 'Agricultural Input Dealer'), ('VET_CLINIC', 'Veterinary Clinic'), ('PHARMACY', 'Agricultural Pharmacy')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='Village, LGA, State', max_length=255)),
                ('region_code', models.CharField(help_text='e.g., NG-KD', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['-is_verified', '-rating'],
                'indexes': [models.Index(fields=['region_code'], name='vendors_region__df6054_idx'), models.Index(fields=['vendor_type'], name='vendors_vendor__7b13ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from farmer to vendor', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_vendors', to='core.diagnosis')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
            options={
                'db_table': 'diagnosis_vendors',
                'ordering': ['distance_km'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['farmer', '-created_at'], name='diagnoses_farmer__c7f3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['disease'], name='diagnoses_disease_d12112_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['region_code'], name='diagnoses_region__0a9ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['created_at'], name='diagnoses_created_f2a516_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisvendor',
            unique_together={('diagnosis', 'vendor')},
        ),
    ]
