"""Crop classes and treatment metadata aligned with the trained YOLO model."""

CROP_CLASS_CATALOG = {
    "Cashew anthracnose": {
        "scientific_name": "Colletotrichum gloeosporioides",
        "description": "Fungal cashew disease that causes dark sunken lesions on leaves, shoots, flowers, and nuts.",
        "symptoms": "Dark necrotic leaf spots, twig dieback, flower blight, fruit lesions, premature nut drop",
        "causes": "Fungal infection favored by humid weather, dense canopy, rain splash, and infected crop debris",
        "prevention_tips": "Prune crowded canopy, remove infected debris, improve airflow, and avoid overhead irrigation",
        "severity_level": 4,
        "treatments": [{
            "medicine_name": "Copper-based fungicide",
            "active_ingredient": "Copper oxychloride or copper hydroxide",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray covering leaves, flowers, and young nuts",
            "frequency": "Every 7-10 days during active infection",
            "duration": "2-4 applications",
            "precautions": "Prune affected parts and avoid spraying during rain",
            "effectiveness_rating": 4,
        }],
    },
    "Cashew gumosis": {
        "scientific_name": "Lasiodiplodia theobromae complex",
        "description": "Cashew stem and branch disorder marked by gum exudation and bark cracking.",
        "symptoms": "Gum oozing from bark, stem cankers, branch dieback, bark splitting, reduced tree vigor",
        "causes": "Fungal infection entering through wounds, poor drainage, pruning injury, or plant stress",
        "prevention_tips": "Avoid trunk wounds, disinfect pruning tools, improve drainage, and remove badly infected branches",
        "severity_level": 4,
        "treatments": [{
            "medicine_name": "Copper fungicide and sanitation",
            "active_ingredient": "Copper-based fungicide",
            "dosage": "Follow product label rate",
            "application_method": "Clean infected bark and apply protective treatment",
            "frequency": "Monitor weekly",
            "duration": "Until gum exudation stops",
            "precautions": "Avoid stem injuries and improve drainage",
            "effectiveness_rating": 3,
        }],
    },
    "Cashew healthy": {
        "scientific_name": "",
        "description": "Healthy cashew foliage without visible pest or disease symptoms.",
        "symptoms": "Green leaves, normal canopy growth, no visible lesions or pest mining",
        "causes": "No disease detected",
        "prevention_tips": "Continue balanced nutrition, sanitation, scouting, and proper pruning",
        "severity_level": 1,
        "treatments": [{
            "medicine_name": "No treatment needed",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Continue regular crop care",
            "frequency": "Scout weekly",
            "duration": "Ongoing",
            "precautions": "Avoid unnecessary pesticide use",
            "effectiveness_rating": 5,
        }],
    },
    "Cashew leaf miner": {
        "scientific_name": "Leaf-mining insect pest",
        "description": "Cashew leaf pest that tunnels through leaf tissue and reduces photosynthetic area.",
        "symptoms": "Serpentine mines, brown trails inside leaves, distorted young leaves, premature leaf drop",
        "causes": "Larvae feeding between leaf surfaces, often worse on young flushes",
        "prevention_tips": "Scout young leaves, conserve beneficial insects, remove heavily infested leaves",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Recommended systemic insecticide",
            "active_ingredient": "Use locally approved systemic insecticide",
            "dosage": "Follow local extension guidance",
            "application_method": "Target affected leaves",
            "frequency": "Repeat only if infestation persists",
            "duration": "1-2 applications",
            "precautions": "Avoid spraying during flowering where pollinators are active",
            "effectiveness_rating": 3,
        }],
    },
    "Cashew red rust": {
        "scientific_name": "Cephaleuros virescens",
        "description": "Algal leaf spot disease that appears as rusty orange patches on cashew leaves.",
        "symptoms": "Rusty red or orange circular leaf spots, rough leaf patches, reduced leaf vigor",
        "causes": "Algal infection favored by humidity, shade, and poor airflow",
        "prevention_tips": "Prune for airflow, reduce shade, remove severely affected leaves",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Copper oxychloride",
            "active_ingredient": "Copper oxychloride",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray",
            "frequency": "Every 10-14 days",
            "duration": "2-3 applications",
            "precautions": "Remove severely affected leaves",
            "effectiveness_rating": 4,
        }],
    },
    "Cassava bacterial blight": {
        "scientific_name": "Xanthomonas axonopodis pv. manihotis",
        "description": "Bacterial cassava disease that causes angular leaf spots, blight, wilting, and dieback.",
        "symptoms": "Angular water-soaked spots, leaf blight, wilting, stem dieback, gum exudates",
        "causes": "Bacteria spread through infected cuttings, tools, rain splash, and field movement",
        "prevention_tips": "Use clean cuttings, disinfect tools, remove infected plants, and rotate fields",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "Field sanitation and disease-free cuttings",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Remove infected plants and avoid contaminated tools",
            "frequency": "Ongoing monitoring",
            "duration": "Season-long",
            "precautions": "Use resistant varieties where available",
            "effectiveness_rating": 3,
        }],
    },
    "Cassava brown spot": {
        "scientific_name": "Cercospora henningsii",
        "description": "Fungal cassava leaf spot that causes brown lesions and early defoliation.",
        "symptoms": "Brown leaf spots with darker margins, yellowing, leaf drop, reduced canopy",
        "causes": "Fungal spores favored by humidity and dense canopy",
        "prevention_tips": "Improve spacing, remove infected leaves, plant tolerant varieties",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Mancozeb or copper-based fungicide",
            "active_ingredient": "Mancozeb or copper compound",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray",
            "frequency": "Every 10-14 days",
            "duration": "2-3 applications",
            "precautions": "Improve spacing and remove infected leaves",
            "effectiveness_rating": 3,
        }],
    },
    "Cassava green mite": {
        "scientific_name": "Mononychellus tanajoa",
        "description": "Cassava mite pest that feeds on young leaves and causes speckling and deformation.",
        "symptoms": "Yellow speckling, leaf distortion, bronzing, stunted shoots, webbing in severe attacks",
        "causes": "Mite infestation favored by dry conditions and stressed plants",
        "prevention_tips": "Plant vigorous cuttings, conserve natural enemies, avoid unnecessary insecticides",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Miticide or biological control",
            "active_ingredient": "Use locally approved miticide where needed",
            "dosage": "Follow product label rate",
            "application_method": "Target underside of leaves",
            "frequency": "As infestation requires",
            "duration": "Until mite pressure drops",
            "precautions": "Avoid overuse of broad-spectrum insecticides",
            "effectiveness_rating": 3,
        }],
    },
    "Cassava healthy": {
        "scientific_name": "",
        "description": "Healthy cassava foliage without visible disease or mite symptoms.",
        "symptoms": "Normal leaf color and shape, vigorous shoot growth, no mosaic, spots, or mite damage",
        "causes": "No disease detected",
        "prevention_tips": "Use clean cuttings, scout regularly, and maintain balanced soil fertility",
        "severity_level": 1,
        "treatments": [{
            "medicine_name": "No treatment needed",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Continue regular crop care",
            "frequency": "Scout weekly",
            "duration": "Ongoing",
            "precautions": "Avoid unnecessary pesticide use",
            "effectiveness_rating": 5,
        }],
    },
    "Cassava mosaic": {
        "scientific_name": "Cassava mosaic begomoviruses",
        "description": "Viral cassava disease that causes mosaic leaf patterns and yield loss.",
        "symptoms": "Yellow-green mosaic patterns, distorted leaves, stunted growth, reduced root yield",
        "causes": "Virus transmitted by whiteflies and infected cuttings",
        "prevention_tips": "Use certified disease-free cuttings, control whiteflies, remove infected plants",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "No chemical cure - management only",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Remove infected plants and use disease-free cuttings",
            "frequency": "Regular field monitoring",
            "duration": "Season-long",
            "precautions": "Control whiteflies and plant resistant varieties",
            "effectiveness_rating": 3,
        }],
    },
    "Maize fall armyworm": {
        "scientific_name": "Spodoptera frugiperda",
        "description": "Destructive maize caterpillar pest that feeds heavily in the whorl and on leaves.",
        "symptoms": "Ragged leaf holes, window-paning, frass in whorl, damaged growing point",
        "causes": "Larval feeding by fall armyworm, often severe during early maize growth",
        "prevention_tips": "Scout early, use pheromone traps where available, destroy crop residues",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "Emamectin benzoate or recommended biopesticide",
            "active_ingredient": "Emamectin benzoate or Bacillus thuringiensis",
            "dosage": "Follow product label rate",
            "application_method": "Apply into maize whorl",
            "frequency": "Scout twice weekly and treat early",
            "duration": "Repeat based on scouting",
            "precautions": "Rotate active ingredients to reduce resistance",
            "effectiveness_rating": 4,
        }],
    },
    "Maize grasshoper": {
        "scientific_name": "Grasshopper complex",
        "description": "Maize defoliating insect pest that chews leaf edges and blades.",
        "symptoms": "Irregular leaf chewing, missing leaf edges, defoliation, visible grasshoppers",
        "causes": "Grasshopper feeding, often migrating from surrounding vegetation",
        "prevention_tips": "Control weeds around fields, scout field margins, treat early outbreaks",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Recommended contact insecticide",
            "active_ingredient": "Use locally approved contact insecticide",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray at early infestation",
            "frequency": "As needed after scouting",
            "duration": "1-2 applications",
            "precautions": "Protect beneficial insects where possible",
            "effectiveness_rating": 3,
        }],
    },
    "Maize healthy": {
        "scientific_name": "",
        "description": "Healthy maize foliage without visible disease or insect damage.",
        "symptoms": "Green leaves, no lesions, no feeding holes, normal plant growth",
        "causes": "No disease detected",
        "prevention_tips": "Maintain fertility, scout weekly, and manage weeds",
        "severity_level": 1,
        "treatments": [{
            "medicine_name": "No treatment needed",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Continue regular crop care",
            "frequency": "Scout weekly",
            "duration": "Ongoing",
            "precautions": "Avoid unnecessary pesticide use",
            "effectiveness_rating": 5,
        }],
    },
    "Maize leaf beetle": {
        "scientific_name": "Leaf beetle complex",
        "description": "Maize leaf-feeding beetle damage that causes chewing injury and reduced leaf area.",
        "symptoms": "Shot holes, scraped leaf surfaces, ragged feeding marks, visible beetles",
        "causes": "Adult beetle feeding, often worse in young maize and weedy fields",
        "prevention_tips": "Scout early, control weeds, avoid late planting where pest pressure is high",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Recommended contact or systemic insecticide",
            "active_ingredient": "Use locally approved maize insecticide",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray",
            "frequency": "As needed after scouting",
            "duration": "1-2 applications",
            "precautions": "Treat only when economic damage is visible",
            "effectiveness_rating": 3,
        }],
    },
    "Maize leaf blight": {
        "scientific_name": "Exserohilum turcicum",
        "description": "Fungal maize leaf disease that causes elongated lesions and reduces photosynthesis.",
        "symptoms": "Long elliptical gray-brown lesions, leaf drying, reduced photosynthesis",
        "causes": "Fungal pathogen spread by wind and water splash in humid conditions",
        "prevention_tips": "Use resistant varieties, rotate crops, remove residues, maintain spacing",
        "severity_level": 4,
        "treatments": [{
            "medicine_name": "Mancozeb Fungicide",
            "active_ingredient": "Mancozeb 80% WP",
            "dosage": "2.5 kg per hectare",
            "application_method": "Foliar spray",
            "frequency": "Every 7-10 days",
            "duration": "3-4 weeks",
            "precautions": "Avoid spraying during rain and use protective equipment",
            "effectiveness_rating": 4,
        }],
    },
    "Maize leaf spot": {
        "scientific_name": "Cercospora or Curvularia leaf spot complex",
        "description": "Maize fungal leaf spot condition that causes small necrotic leaf lesions.",
        "symptoms": "Small brown or tan spots, yellow halos, leaf blighting in severe cases",
        "causes": "Fungal infection favored by humidity, crop residue, and poor airflow",
        "prevention_tips": "Rotate crops, improve spacing, remove infected residues",
        "severity_level": 3,
        "treatments": [{
            "medicine_name": "Azoxystrobin or Mancozeb",
            "active_ingredient": "Azoxystrobin or Mancozeb",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray",
            "frequency": "Every 10-14 days",
            "duration": "2-3 applications",
            "precautions": "Improve spacing and rotate crops",
            "effectiveness_rating": 4,
        }],
    },
    "Maize streak virus": {
        "scientific_name": "Maize streak virus",
        "description": "Viral maize disease that causes chlorotic streaks and stunting.",
        "symptoms": "Narrow yellow streaks parallel to veins, stunting, poor cob formation",
        "causes": "Virus transmitted by leafhopper vectors",
        "prevention_tips": "Use resistant varieties, plant early, control leafhopper vectors, remove infected plants",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "Vector management and infected plant removal",
            "active_ingredient": "Leafhopper control using approved insecticide where needed",
            "dosage": "Use recommended insecticide label rate for leafhopper control",
            "application_method": "Remove infected plants and control insect vectors",
            "frequency": "Monitor weekly",
            "duration": "Season-long",
            "precautions": "Use resistant varieties and avoid moving infected plant material",
            "effectiveness_rating": 3,
        }],
    },
    "Tomato healthy": {
        "scientific_name": "",
        "description": "Healthy tomato foliage without visible disease symptoms.",
        "symptoms": "Green leaves, normal leaf shape, no spots, curls, blight, or wilt",
        "causes": "No disease detected",
        "prevention_tips": "Continue sanitation, staking, balanced watering, and routine scouting",
        "severity_level": 1,
        "treatments": [{
            "medicine_name": "No treatment needed",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Continue regular crop care",
            "frequency": "Scout weekly",
            "duration": "Ongoing",
            "precautions": "Avoid unnecessary pesticide use",
            "effectiveness_rating": 5,
        }],
    },
    "Tomato leaf blight": {
        "scientific_name": "Alternaria solani or Phytophthora complex",
        "description": "Tomato blight condition that causes leaf lesions and rapid canopy damage.",
        "symptoms": "Dark leaf spots, yellowing, blighting, defoliation, possible fruit lesions",
        "causes": "Fungal or oomycete infection favored by wet leaves and poor airflow",
        "prevention_tips": "Stake plants, avoid overhead irrigation, remove infected leaves, rotate crops",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "Chlorothalonil or Mancozeb",
            "active_ingredient": "Chlorothalonil or Mancozeb",
            "dosage": "2 kg per hectare",
            "application_method": "Foliar spray",
            "frequency": "Every 7 days",
            "duration": "Until disease pressure reduces",
            "precautions": "Remove infected leaves and avoid overhead irrigation",
            "effectiveness_rating": 4,
        }],
    },
    "Tomato leaf curl": {
        "scientific_name": "Tomato yellow leaf curl virus",
        "description": "Viral tomato disease that causes curling leaves, yellowing, and stunting.",
        "symptoms": "Upward leaf curling, yellowing, small leaves, stunted plants, poor fruit set",
        "causes": "Virus spread mainly by whiteflies and infected seedlings",
        "prevention_tips": "Use resistant seedlings, control whiteflies, rogue infected plants, use insect netting",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "Whitefly control and infected plant removal",
            "active_ingredient": "Approved whitefly insecticide or biocontrol",
            "dosage": "Follow insecticide label rate",
            "application_method": "Control whitefly vectors and rogue infected plants",
            "frequency": "Monitor weekly",
            "duration": "Season-long",
            "precautions": "Use resistant seedlings where available",
            "effectiveness_rating": 3,
        }],
    },
    "Tomato septoria leaf spot": {
        "scientific_name": "Septoria lycopersici",
        "description": "Fungal tomato disease causing many small leaf spots and lower-leaf defoliation.",
        "symptoms": "Small circular leaf spots with gray centers, yellow halos, lower leaf drop",
        "causes": "Fungal spores spread by rain splash, infected debris, and humid conditions",
        "prevention_tips": "Mulch soil, remove lower infected leaves, improve airflow, rotate crops",
        "severity_level": 4,
        "treatments": [{
            "medicine_name": "Copper fungicide or Chlorothalonil",
            "active_ingredient": "Copper compound or Chlorothalonil",
            "dosage": "Follow product label rate",
            "application_method": "Foliar spray",
            "frequency": "Every 7-10 days",
            "duration": "2-4 applications",
            "precautions": "Remove lower infected leaves and mulch soil",
            "effectiveness_rating": 4,
        }],
    },
    "Tomato_verticulium_wilt": {
        "scientific_name": "Verticillium dahliae",
        "description": "Soil-borne tomato wilt disease that causes yellowing, wilting, and reduced yield.",
        "symptoms": "Lower leaf yellowing, V-shaped lesions, daytime wilting, brown vascular tissue",
        "causes": "Soil-borne fungus persisting in infected soil and crop residue",
        "prevention_tips": "Rotate with non-host crops, use resistant varieties, remove infected plants",
        "severity_level": 5,
        "treatments": [{
            "medicine_name": "No curative chemical treatment",
            "active_ingredient": "N/A",
            "dosage": "N/A",
            "application_method": "Remove infected plants and rotate crops",
            "frequency": "Season-long management",
            "duration": "Multiple seasons of rotation",
            "precautions": "Use resistant varieties and avoid planting tomato repeatedly in same soil",
            "effectiveness_rating": 3,
        }],
    },
}


def get_crop_class_names():
    """Return model class names in trained index order."""
    return list(CROP_CLASS_CATALOG.keys())


def get_crop_catalog_entry(name):
    """Return catalog metadata for a class name with underscore-insensitive matching."""
    canonical_name = get_canonical_crop_class_name(name)
    if canonical_name:
        return CROP_CLASS_CATALOG[canonical_name]

    return None


def get_canonical_crop_class_name(name):
    """Return the exact trained class spelling for an incoming model label."""
    if name in CROP_CLASS_CATALOG:
        return name

    normalized = name.lower().replace("_", " ")
    for class_name in CROP_CLASS_CATALOG:
        if class_name.lower().replace("_", " ") == normalized:
            return class_name

    return None
